# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI Docker Web Vault
on:
  push:
    tags:
    - '*'
jobs:
  docker-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        networks: [
          {network: "0", nodeUrl: "https://nodes.havenprotocol.org:443", tag: "flux-mainnet-latest"},
          {network: "0", nodeUrl: "", tag: "mainnet-latest"},
          {network: "0", nodeUrl: "", tag: "latest"},
          {network: "1", nodeUrl: "https://nodes-testnet.havenprotocol.org:443", tag: "flux-testnet-latest"},
          {network: "1", nodeUrl: "", tag: "testnet-latest"},
          {network: "2", nodeUrl: "https://nodes-stagenet.havenprotocol.org:443", tag: "flux-stagenet-latest"},
          {network: "2", nodeUrl: "", tag: "stagenet-latest"}
        ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_REPO }}:${{matrix.networks.tag}}
          file: client/.docker/Dockerfile
          context: client/
          build-args: |
            REACT_APP_NET_TYPE_ID=${{matrix.networks.network}}
            REACT_APP_HAVEN_DIRECT_HOST=${{matrix.networks.nodeUrl}}